# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changepasswordpart2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(275, 168)
        font = QtGui.QFont()
        font.setPointSize(8)
        Dialog.setFont(font)
        self.part2 = QtWidgets.QWidget(Dialog)
        self.part2.setGeometry(QtCore.QRect(10, 10, 261, 151))
        self.part2.setObjectName("part2")
        self.yenilbl = QtWidgets.QLabel(self.part2)
        self.yenilbl.setGeometry(QtCore.QRect(0, 0, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yenilbl.setFont(font)
        self.yenilbl.setObjectName("yenilbl")
        self.newpasswordtxt = QtWidgets.QLineEdit(self.part2)
        self.newpasswordtxt.setGeometry(QtCore.QRect(130, 10, 111, 20))
        self.newpasswordtxt.setToolTip("")
        self.newpasswordtxt.setWhatsThis("")
        self.newpasswordtxt.setText("")
        self.newpasswordtxt.setFrame(True)
        self.newpasswordtxt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpasswordtxt.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.newpasswordtxt.setClearButtonEnabled(True)
        self.newpasswordtxt.setObjectName("newpasswordtxt")
        self.pswkydbtn = QtWidgets.QPushButton(self.part2)
        self.pswkydbtn.setGeometry(QtCore.QRect(90, 100, 75, 23))
        self.pswkydbtn.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 85, 255);")
        self.pswkydbtn.setObjectName("pswkydbtn")
        self.yenilbl2 = QtWidgets.QLabel(self.part2)
        self.yenilbl2.setGeometry(QtCore.QRect(0, 50, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yenilbl2.setFont(font)
        self.yenilbl2.setObjectName("yenilbl2")
        self.newpaswordtxt2 = QtWidgets.QLineEdit(self.part2)
        self.newpaswordtxt2.setGeometry(QtCore.QRect(130, 52, 111, 20))
        self.newpaswordtxt2.setToolTip("")
        self.newpaswordtxt2.setWhatsThis("")
        self.newpaswordtxt2.setText("")
        self.newpaswordtxt2.setFrame(True)
        self.newpaswordtxt2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpaswordtxt2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.newpaswordtxt2.setClearButtonEnabled(True)
        self.newpaswordtxt2.setObjectName("newpaswordtxt2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.yenilbl.setText(_translate("Dialog", "Yeni Şifrenizi giriniz:"))
        self.newpasswordtxt.setPlaceholderText(_translate("Dialog", "Şifrenizi giriniz"))
        self.pswkydbtn.setText(_translate("Dialog", "Kaydet"))
        self.yenilbl2.setText(_translate("Dialog", "Tekrar giriniz:"))
        self.newpaswordtxt2.setPlaceholderText(_translate("Dialog", "Şifrenizi giriniz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
