# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gelirdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import UDMK
import pymysql
import sys


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(628, 436)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/revenue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gelirlbl = QtWidgets.QLabel(Dialog)
        self.gelirlbl.setGeometry(QtCore.QRect(260, 10, 101, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 45, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 22, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 0, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 0, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 127, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 45, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 22, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 0, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 0, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 127, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 45, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 22, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 0, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 0, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.gelirlbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(24)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.gelirlbl.setFont(font)
        self.gelirlbl.setStyleSheet("color: rgb(0, 170, 0)")
        self.gelirlbl.setObjectName("gelirlbl")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(0, 30, 621, 411))
        self.widget_2.setObjectName("widget_2")
        self.musterilbl2 = QtWidgets.QLabel(self.widget_2)
        self.musterilbl2.setGeometry(QtCore.QRect(30, 20, 61, 31))
        self.musterilbl2.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.musterilbl2.setObjectName("musterilbl2")
        self.musteritxt2 = QtWidgets.QLineEdit(self.widget_2)
        self.musteritxt2.setGeometry(QtCore.QRect(30, 50, 201, 31))
        self.musteritxt2.setObjectName("musteritxt2")
        self.acklamatxt2 = QtWidgets.QTextEdit(self.widget_2)
        self.acklamatxt2.setGeometry(QtCore.QRect(30, 130, 361, 161))
        self.acklamatxt2.setObjectName("acklamatxt2")
        self.acklamalbl2 = QtWidgets.QLabel(self.widget_2)
        self.acklamalbl2.setGeometry(QtCore.QRect(30, 100, 61, 31))
        self.acklamalbl2.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.acklamalbl2.setObjectName("acklamalbl2")
        self.urunlercombobx2 = QtWidgets.QComboBox(self.widget_2)
        self.urunlercombobx2.setGeometry(QtCore.QRect(420, 130, 111, 31))
        self.urunlercombobx2.setObjectName("urunlercombobx2")
        self.urunlercombobx2.addItem("")
        self.urunlercombobx2.addItem("")
        self.urunlercombobx2.addItem("")
        self.urunlercombobx2.addItem("")
        self.urunlercombobx2.addItem("")
        self.urunlerlbl2 = QtWidgets.QLabel(self.widget_2)
        self.urunlerlbl2.setGeometry(QtCore.QRect(420, 100, 61, 31))
        self.urunlerlbl2.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.urunlerlbl2.setObjectName("urunlerlbl2")
        self.tarihlbl2 = QtWidgets.QLabel(self.widget_2)
        self.tarihlbl2.setGeometry(QtCore.QRect(420, 20, 71, 31))
        self.tarihlbl2.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.tarihlbl2.setObjectName("tarihlbl2")
        self.tarihedit2 = QtWidgets.QDateEdit(self.widget_2)
        self.tarihedit2.setGeometry(QtCore.QRect(420, 50, 181, 31))
        self.tarihedit2.setAutoFillBackground(False)
        self.tarihedit2.setInputMethodHints(QtCore.Qt.ImhDate)
        self.tarihedit2.setWrapping(False)
        self.tarihedit2.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.tarihedit2.setCalendarPopup(True)
        self.tarihedit2.setTimeSpec(QtCore.Qt.LocalTime)
        self.tarihedit2.setDate(QtCore.QDate.currentDate())
        self.tarihedit2.setObjectName("tarihedit2")
        self.miktartxt2 = QtWidgets.QLineEdit(self.widget_2)
        self.miktartxt2.setGeometry(QtCore.QRect(420, 190, 81, 31))
        self.miktartxt2.setObjectName("miktartxt2")
        self.miktarcombobx2 = QtWidgets.QComboBox(self.widget_2)
        self.miktarcombobx2.setGeometry(QtCore.QRect(500, 190, 81, 31))
        self.miktarcombobx2.setObjectName("miktarcombobx2")
        self.miktarcombobx2.addItem("")
        self.miktarcombobx2.addItem("")
        self.miktarcombobx2.addItem("")
        self.miktarlbl2 = QtWidgets.QLabel(self.widget_2)
        self.miktarlbl2.setGeometry(QtCore.QRect(420, 160, 71, 31))
        self.miktarlbl2.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.miktarlbl2.setObjectName("miktarlbl2")
        self.fiyattxt2 = QtWidgets.QLineEdit(self.widget_2)
        self.fiyattxt2.setGeometry(QtCore.QRect(420, 260, 81, 31))
        self.fiyattxt2.setPlaceholderText("")
        self.fiyattxt2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.fiyattxt2.setClearButtonEnabled(False)
        self.fiyattxt2.setObjectName("fiyattxt2")
        self.fiyatlarbombobx2 = QtWidgets.QComboBox(self.widget_2)
        self.fiyatlarbombobx2.setGeometry(QtCore.QRect(500, 260, 81, 31))
        self.fiyatlarbombobx2.setObjectName("fiyatlarbombobx2")
        self.fiyatlarbombobx2.addItem("")
        self.fiyatlarbombobx2.addItem("")
        self.fiyatlarbombobx2.addItem("")
        self.fiyatlbl2 = QtWidgets.QLabel(self.widget_2)
        self.fiyatlbl2.setGeometry(QtCore.QRect(420, 230, 101, 31))
        self.fiyatlbl2.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.fiyatlbl2.setObjectName("fiyatlbl2")
        self.temizlebtn2 = QtWidgets.QPushButton(self.widget_2)
        self.temizlebtn2.setGeometry(QtCore.QRect(220, 350, 91, 31))
        self.temizlebtn2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 85, 255);")
        self.temizlebtn2.clicked.connect(self.temizlecliked)
        self.temizlebtn2.setObjectName("temizlebtn2")
        self.kaydetbtn2 = QtWidgets.QPushButton(self.widget_2)
        self.kaydetbtn2.setGeometry(QtCore.QRect(330, 350, 91, 31))
        self.kaydetbtn2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 85, 255);")
        self.kaydetbtn2.clicked.connect(self.mgirdikydt)
        self.kaydetbtn2.setObjectName("kaydetbtn2")
        self.msteribtnekle = QtWidgets.QPushButton(self.widget_2)
        self.msteribtnekle.setGeometry(QtCore.QRect(290, 50, 81, 31))
        self.msteribtnekle.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 85, 255);")
        self.msteribtnekle.setObjectName("msteribtnekle")
        self.msteribtnekle.clicked.connect(self.mdtkcliked)
        self.msteribtnekle.setObjectName("msteribtnekle")
        self.kisibilgibtn2 = QtWidgets.QPushButton(self.widget_2)
        self.kisibilgibtn2.setGeometry(QtCore.QRect(240, 50, 41, 31))
        self.kisibilgibtn2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                         "alternate-background-color: rgb(0, 85, 255);")
        self.kisibilgibtn2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kisibilgibtn2.setIcon(icon1)
        self.kisibilgibtn2.setIconSize(QtCore.QSize(20, 20))
        self.kisibilgibtn2.setObjectName("kisibilgibtn2")
        #self.kisibilgibtn2.setCheckable(True)
        #self.kisibilgibtn2.clicked['bool'].connect(self.infocliled)
        self.kisibilgibtn2.pressed.connect(self.infocliled)
        self.kisibilgibtn2.released.connect(self.notinfocliked)
        self.satsinfolbl = QtWidgets.QLabel(self.widget_2)
        self.satsinfolbl.setGeometry(QtCore.QRect(220, 310, 201, 30))
        self.satsinfolbl.setObjectName("satsinlbl")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        ##completer
        db = pymysql.connect(host='127.0.0.1',
                             user='root',
                             password='',
                             db='test',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor
                             )
        baglanti = db.cursor()

        baglanti.execute(f'SELECT MAdSoyad FROM musteri')
        scomp = baglanti.fetchall()

        names = []
        x = 0

        for i in scomp:
            names.append(scomp[x]['MAdSoyad'])
            x += 1

        completer = QtWidgets.QCompleter(names)
        self.musteritxt2.setCompleter(completer)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MÜŞTERİ"))
        self.gelirlbl.setWhatsThis(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-style:italic; text-decoration: underline; color:#00aa00;\">GELİR</span></p></body></html>"))
        self.gelirlbl.setText(_translate("Dialog", "MÜŞTERİ"))
        self.musterilbl2.setText(_translate("Dialog", "MÜŞTERİ"))
        self.acklamalbl2.setText(_translate("Dialog", "AÇIKLAMA"))
        self.urunlercombobx2.setItemText(0, _translate("Dialog", "ODUN"))
        self.urunlercombobx2.setItemText(1, _translate("Dialog", "FINDIK"))
        self.urunlercombobx2.setItemText(2, _translate("Dialog", "UN"))
        self.urunlercombobx2.setItemText(3, _translate("Dialog", "BUGDAY"))
        self.urunlercombobx2.setItemText(4, _translate("Dialog", "ARPA"))
        self.urunlerlbl2.setText(_translate("Dialog", "ÜRÜNLER"))
        self.tarihlbl2.setText(_translate("Dialog", "TARİH"))
        self.miktarcombobx2.setItemText(0, _translate("Dialog", "Kilogram"))
        self.miktarcombobx2.setItemText(1, _translate("Dialog", "Gram"))
        self.miktarcombobx2.setItemText(2, _translate("Dialog", "Litre"))
        self.miktarlbl2.setText(_translate("Dialog", " MİKTAR"))
        self.fiyatlarbombobx2.setItemText(0, _translate("Dialog", "Türk Lirası ₺"))
        self.fiyatlarbombobx2.setItemText(1, _translate("Dialog", "Dolar $"))
        self.fiyatlarbombobx2.setItemText(2, _translate("Dialog", "Euro €"))
        self.fiyatlbl2.setText(_translate("Dialog", "BİRİM FİYATI"))
        self.temizlebtn2.setText(_translate("Dialog", "Temizle"))
        self.kaydetbtn2.setText(_translate("Dialog", "Kaydet"))
        self.msteribtnekle.setText(_translate("Dialog", "MÜŞTERİ EKLE"))


    def mdtkcliked(self):
        self.mkDialog = QtWidgets.QDialog()
        self.ui = UDMK.Ui_Dialog()
        self.ui.setupUi(self.mkDialog)
        self.mkDialog.show()

    def mgirdikydt(self):
       try:
        _translate = QtCore.QCoreApplication.translate
        self.satsinfolbl.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                                       "color: rgb(0, 170, 0);")
        self.satsinfolbl.setText(_translate("Dialog", "   Satış başarıyla kaydedildi."))
        db = pymysql.connect(host='127.0.0.1',
                             user='root',
                             password='',
                             db='test',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor
                             )
        baglanti = db.cursor()
        midtxt=self.musteritxt2.text()
        baglanti.execute(f'SELECT MID FROM musteri WHERE MAdSoyad="{midtxt}" ')
        index = baglanti.fetchall()
        mid=int(index[0]['MID'])
        uidtxt=str(self.urunlercombobx2.currentText())
        baglanti.execute(f'SELECT UID FROM urunler WHERE  UrunAd="{uidtxt}" ')
        uindex=baglanti.fetchall()
        uid=int(uindex[0]['UID'])
        umiktar=int(self.miktartxt2.text())
        umiktarbirim=str(self.miktarcombobx2.currentText())
        ubirimfiyat=int(self.fiyattxt2.text())
        ufiyatbirim=str(self.fiyatlarbombobx2.currentText())
        gtarih=self.tarihedit2.date().toPyDate()
        gaciklama=self.acklamatxt2.toPlainText()
        tutar=umiktar*ubirimfiyat

        baglanti.execute(f"INSERT INTO musterigirdi (MID,UID,UMiktar,Umiktarbirim,UBirimFiyat,Ufiyatbirim,GTarih,GAcıklama,GTutar) VALUES ('{mid}','{uid}','{umiktar}','{umiktarbirim}','{ubirimfiyat}','{ufiyatbirim}','{gtarih}','{gaciklama}','{tutar}')")

        db.commit()

        #stok güncelleme
        if str(self.urunlercombobx2.currentText()) == 'FINDIK':
            baglanti.execute('SELECT SUM(UMiktar) FROM tedarikgirdi WHERE UID="1"')
            updtadepo1 = baglanti.fetchall()
            ss1 = int(updtadepo1[0]['SUM(UMiktar)'])
            ##
            baglanti.execute('SELECT SUM(UMiktar) FROM musterigirdi WHERE UID="1"')
            mupdtadepo1 = baglanti.fetchall()
            mss = int(mupdtadepo1[0]['SUM(UMiktar)'])
            mtss = ss1 - mss
            baglanti.execute(f"UPDATE depo SET UStok='{mtss}' WHERE UID='1'")
            db.commit()

        elif str(self.urunlercombobx2.currentText()) == 'ODUN':
            baglanti.execute('SELECT SUM(UMiktar) FROM tedarikgirdi WHERE UID="2"')
            updtadepo2 = baglanti.fetchall()
            ss2 = int(updtadepo2[0]['SUM(UMiktar)'])
            baglanti.execute('SELECT SUM(UMiktar) FROM musterigirdi WHERE UID="2"')
            mupdtadepo2 = baglanti.fetchall()
            mss1 = int(mupdtadepo2[0]['SUM(UMiktar)'])
            mtss1 = ss2 - mss1
            baglanti.execute(f"UPDATE depo SET UStok='{mtss1}' WHERE UID='2'")
            db.commit()
        elif str(self.urunlercombobx2.currentText()) == 'BUGDAY':
            baglanti.execute('SELECT SUM(UMiktar) FROM tedarikgirdi WHERE UID="3"')
            updtadepo3 = baglanti.fetchall()
            ss3 = int(updtadepo3[0]['SUM(UMiktar)'])
            baglanti.execute('SELECT SUM(UMiktar) FROM musterigirdi WHERE UID="3"')
            mupdtadepo3 = baglanti.fetchall()
            mss2 = int(mupdtadepo3[0]['SUM(UMiktar)'])
            mtss2 = ss3 - mss2
            baglanti.execute(f"UPDATE depo SET UStok='{mtss2}' WHERE UID='3'")
            db.commit()

        elif str(self.urunlercombobx2.currentText()) == 'ARPA':
            baglanti.execute('SELECT SUM(UMiktar) FROM tedarikgirdi WHERE UID="4"')
            updtadepo4 = baglanti.fetchall()
            ss4 = int(updtadepo4[0]['SUM(UMiktar)'])
            baglanti.execute('SELECT SUM(UMiktar) FROM musterigirdi WHERE UID="4"')
            mupdtadepo4 = baglanti.fetchall()
            mss3 = int(mupdtadepo4[0]['SUM(UMiktar)'])
            mtss3 = ss4 - mss3
            baglanti.execute(f"UPDATE depo SET UStok='{mtss3}' WHERE UID='4'")
            db.commit()
        elif str(self.urunlercombobx2.currentText()) == 'UN':
            baglanti.execute('SELECT SUM(UMiktar) FROM tedarikgirdi WHERE UID="5"')
            updtadepo5 = baglanti.fetchall()
            ss5 = int(updtadepo5[0]['SUM(UMiktar)'])
            baglanti.execute('SELECT SUM(UMiktar) FROM musterigirdi WHERE UID="5"')
            mupdtadepo5 = baglanti.fetchall()
            mss4 = int(mupdtadepo5[0]['SUM(UMiktar)'])
            mtss4 = ss5 - mss4
            baglanti.execute(f"UPDATE depo SET UStok='{mtss4}' WHERE UID='5'")
            db.commit()




       except ValueError as e:
           self.satsinfolbl.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
                                          "color: rgb(255, 0, 0);")
           self.satsinfolbl.setText(_translate("Dialog", f"Başında yıldız olan alanlar boş bırakılamaz!"))
       except IndexError as f:
           self.satsinfolbl.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
                                             "color: rgb(255, 0, 0);")
           self.satsinfolbl.setText(_translate("Dialog", f"Böyle bir müşteri kayıt edilmemiş\nÖnce kayıt ediniz"))
       except AttributeError as g:
           self.satsinfolbl.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
                                             "color: rgb(255, 0, 0);")
           self.satsinfolbl.setText(_translate("Dialog", f"Başında yıldız olan alanlar boş bırakılamaz!"))



    def temizlecliked(self):
        _translate = QtCore.QCoreApplication.translate
        self.satsinfolbl.setText(_translate("Dialog", ""))
        self.musteritxt2.setText("")
        self.acklamatxt2.setText("")
        self.miktartxt2.setText("")
        self.fiyattxt2.setText("")
        self.tarihedit2.setDate(QtCore.QDate.currentDate())
        self.miktarcombobx2.setCurrentIndex(0)
        self.fiyatlarbombobx2.setCurrentIndex(0)
        self.urunlercombobx2.setCurrentIndex(0)

    def infocliled(self):
        ##database insert
        db = pymysql.connect(host='127.0.0.1',
                             user='root',
                             password='',
                             db='test',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor
                             )
        baglanti = db.cursor()

        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setGeometry(QtCore.QRect(30, 81, 251, 151))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "background-color: rgb(188, 189, 198);\n"
                                 "")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
                                 "font: 75 8pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 25, 161, 21))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 50, 171, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(0, 110, 181, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(0, 75, 171, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(110, 0, 111, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(70, 25, 181, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(80, 50, 191, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(80, 75, 171, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(80, 100, 171, 41))
        self.label_10.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_10.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")


        self.label.setText(( "Müşteri İsim/Soyisim :"))
        self.label_2.setText( "Müşteri Tel :")
        self.label_3.setText( "Müşteri Email :")
        self.label_4.setText( "Müşteri Adres :")
        self.label_5.setText( "Müşteri İl/İlçe:")

        midtxt = self.musteritxt2.text()
        baglanti.execute(f'SELECT MAdSoyad,MTel,MEmail,Mil,MIlce,MAdres FROM musteri WHERE MAdSoyad="{midtxt}" ')
        isim = baglanti.fetchall()


        if self.musteritxt2.text()=='':
            self.label_6.setText("")
            self.label_7.setText("")
            self.label_8.setText("")
            self.label_9.setText("")
            self.label_10.setText("")
        else:
           self.label_6.setText( f"{isim[0]['MAdSoyad']}")
           self.label_7.setText( f"{isim[0]['MTel']}")
           self.label_8.setText( f"{isim[0]['MEmail']}")
           self.label_9.setText( f"{isim[0]['Mil']}/{isim[0]['MIlce']}")
           self.label_10.setText( f"{isim[0]['MAdres']}")

        self.frame.show()

    def notinfocliked(self):
        self.frame.close()






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mDialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(mDialog)
    mDialog.show()
    sys.exit(app.exec_())
