# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'musterikaytdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql




class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(324, 332)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/people.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 311, 341))
        self.widget.setObjectName("widget")
        self.mstrerisimlbl = QtWidgets.QLabel(self.widget)
        self.mstrerisimlbl.setGeometry(QtCore.QRect(10, 0, 81, 21))
        self.mstrerisimlbl.setObjectName("mstrerisimlbl")
        self.musterisimtxt = QtWidgets.QLineEdit(self.widget)
        self.musterisimtxt.setGeometry(QtCore.QRect(10, 20, 111, 20))
        self.musterisimtxt.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.musterisimtxt.setObjectName("musterisimtxt")
        self.adreslbl = QtWidgets.QLabel(self.widget)
        self.adreslbl.setGeometry(QtCore.QRect(10, 150, 41, 16))
        self.adreslbl.setObjectName("adreslbl")
        self.soyisimlbl = QtWidgets.QLabel(self.widget)
        self.soyisimlbl.setGeometry(QtCore.QRect(10, 50, 51, 21))
        self.soyisimlbl.setObjectName("soyisimlbl")
        self.iltxt = QtWidgets.QLineEdit(self.widget)
        self.iltxt.setGeometry(QtCore.QRect(10, 120, 113, 20))
        self.iltxt.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.iltxt.setObjectName("iltxt")
        self.ilcetxt = QtWidgets.QLineEdit(self.widget)
        self.ilcetxt.setGeometry(QtCore.QRect(170, 120, 121, 20))
        self.ilcetxt.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.ilcetxt.setObjectName("ilcetxt")
        self.teltxt = QtWidgets.QLineEdit(self.widget)
        self.teltxt.setGeometry(QtCore.QRect(170, 20, 121, 20))
        self.teltxt.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.teltxt.setObjectName("teltxt")
        self.illbl = QtWidgets.QLabel(self.widget)
        self.illbl.setGeometry(QtCore.QRect(10, 100, 51, 20))
        self.illbl.setObjectName("illbl")
        self.ilcelbl = QtWidgets.QLabel(self.widget)
        self.ilcelbl.setGeometry(QtCore.QRect(170, 100, 41, 16))
        self.ilcelbl.setObjectName("ilcelbl")
        self.soyisimtxt = QtWidgets.QLineEdit(self.widget)
        self.soyisimtxt.setGeometry(QtCore.QRect(10, 70, 111, 20))
        self.soyisimtxt.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.soyisimtxt.setObjectName("soyisimtxt")
        self.adrestxt = QtWidgets.QPlainTextEdit(self.widget)
        self.adrestxt.setGeometry(QtCore.QRect(10, 170, 281, 81))
        self.adrestxt.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.adrestxt.setObjectName("adrestxt")
        self.tellbl = QtWidgets.QLabel(self.widget)
        self.tellbl.setGeometry(QtCore.QRect(170, 0, 51, 21))
        self.tellbl.setObjectName("tellbl")
        self.emaillbl = QtWidgets.QLabel(self.widget)
        self.emaillbl.setGeometry(QtCore.QRect(170, 50, 47, 13))
        self.emaillbl.setObjectName("emaillbl")
        self.emailtxt = QtWidgets.QLineEdit(self.widget)
        self.emailtxt.setGeometry(QtCore.QRect(170, 70, 121, 20))
        self.emailtxt.setStyleSheet("")
        self.emailtxt.setObjectName("emailtxt")
        self.msterigirditmzlebtn = QtWidgets.QPushButton(self.widget)
        self.msterigirditmzlebtn.setGeometry(QtCore.QRect(60, 280, 75, 23))
        self.msterigirditmzlebtn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 85, 255);")
        self.msterigirditmzlebtn.setObjectName("msterigirditmzlebtn")
        self.msterigirditmzlebtn.clicked.connect(self.temizlecliked)
        self.musterikydetbtn = QtWidgets.QPushButton(self.widget)
        self.musterikydetbtn.setGeometry(QtCore.QRect(160, 280, 75, 23))
        self.musterikydetbtn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 85, 255);")
        self.musterikydetbtn.setObjectName("musterikydetbtn")
        self.musterikydetbtn.clicked.connect(self.mkayt)
        self.kytinfolbl = QtWidgets.QLabel(self.widget)
        self.kytinfolbl.setGeometry(QtCore.QRect(62, 255, 181, 20))
        self.kytinfolbl.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
                                      "color: rgb(0, 170, 0);")
        self.kytinfolbl.setObjectName("kytinfolbl")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MÜŞTERİ EKLE"))
        self.mstrerisimlbl.setText(_translate("Dialog", "MÜŞTERİ İSİM"))
        self.adreslbl.setText(_translate("Dialog", "ADRES"))
        self.soyisimlbl.setText(_translate("Dialog", "SOYİSİM"))
        self.illbl.setText(_translate("Dialog", "İL"))
        self.ilcelbl.setText(_translate("Dialog", "İLÇE"))
        self.adrestxt.setPlainText(_translate("Dialog", "\n"
""))
        self.tellbl.setText(_translate("Dialog", "TELEFON"))
        self.emaillbl.setText(_translate("Dialog", "EMAİL"))
        self.msterigirditmzlebtn.setText(_translate("Dialog", "TEMİZLE"))
        self.musterikydetbtn.setText(_translate("Dialog", "KAYDET"))


    def mkayt(self):
        _translate = QtCore.QCoreApplication.translate
        if  self.musterisimtxt.text()=='' or self.soyisimtxt.text()=='' or self.teltxt.text()=='' or self.emailtxt.text()=='' or self.iltxt.text()=='' or self.ilcetxt.text()=='' or self.adrestxt.toPlainText()=='' :
            self.kytinfolbl.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
                                          "color: rgb(255, 0, 0);")
            self.kytinfolbl.setText(_translate("Dialog", "Boş Alanlar var!"))
            self.kytinfolbl.setAlignment(QtCore.Qt.AlignCenter)

        else:
            self.kytinfolbl.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
                                          "color: rgb(0, 170, 0);")
            self.kytinfolbl.setText(_translate("Dialog", "Müşteri başarılı bir şekilde kayıt oldu."))
            db = pymysql.connect(host='127.0.0.1',
                                 user='root',
                                 password='',
                                 db='test',
                                 charset='utf8mb4',
                                 cursorclass=pymysql.cursors.DictCursor
                                 )
            baglanti = db.cursor()
            mad = self.musterisimtxt.text()
            msoyad = self.soyisimtxt.text()
            mtel = self.teltxt.text()
            memail = self.emailtxt.text()
            mil = self.iltxt.text()
            milce = self.ilcetxt.text()
            madres = self.adrestxt.toPlainText()


            baglanti.execute(f"INSERT INTO musteri (MAdSoyad,MTel,MEmail,Mil,MIlce,MAdres) VALUES ('{mad+' '+msoyad}','{mtel}','{memail}','{mil}','{milce}','{madres}')")

            db.commit()


    def temizlecliked(self):
        _translate = QtCore.QCoreApplication.translate
        self.kytinfolbl.setText(_translate("Dialog", ""))
        self.musterisimtxt.setText("")
        self.soyisimtxt.setText("")
        self.teltxt.setText("")
        self.emailtxt.setText("")
        self.iltxt.setText("")
        self.ilcetxt.setText("")
        self.adrestxt.setPlainText("")






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mkDialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(mkDialog)
    mkDialog.show()
    sys.exit(app.exec_())
