# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giderdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import UDTK
import pymysql
import UDM,UM

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(630, 436)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/stock-market.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 30, 628, 401))
        self.widget.setObjectName("widget")
        self.tedarikcilbl = QtWidgets.QLabel(self.widget)
        self.tedarikcilbl.setGeometry(QtCore.QRect(30, 20, 71, 31))
        self.tedarikcilbl.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.tedarikcilbl.setObjectName("tedarikcilbl")
        self.tedarikcitxt = QtWidgets.QLineEdit(self.widget)
        self.tedarikcitxt.setGeometry(QtCore.QRect(30, 50, 201, 31))
        self.tedarikcitxt.setObjectName("tedarikcitxt")
        self.acklamatxt = QtWidgets.QTextEdit(self.widget)
        self.acklamatxt.setGeometry(QtCore.QRect(30, 130, 361, 161))
        self.acklamatxt.setObjectName("acklamatxt")
        self.acklamalbl = QtWidgets.QLabel(self.widget)
        self.acklamalbl.setGeometry(QtCore.QRect(30, 100, 61, 31))
        self.acklamalbl.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.acklamalbl.setObjectName("acklamalbl")
        self.urunlercombobx = QtWidgets.QComboBox(self.widget)
        self.urunlercombobx.setGeometry(QtCore.QRect(420, 130, 111, 31))
        self.urunlercombobx.setObjectName("urunlercombobx")
        self.urunlercombobx.addItem("")
        self.urunlercombobx.addItem("")
        self.urunlercombobx.addItem("")
        self.urunlercombobx.addItem("")
        self.urunlercombobx.addItem("")
        self.urunlerlbl = QtWidgets.QLabel(self.widget)
        self.urunlerlbl.setGeometry(QtCore.QRect(420, 100, 61, 31))
        self.urunlerlbl.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.urunlerlbl.setObjectName("urunlerlbl")
        self.tarihlbl = QtWidgets.QLabel(self.widget)
        self.tarihlbl.setGeometry(QtCore.QRect(420, 20, 71, 31))
        self.tarihlbl.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.tarihlbl.setObjectName("tarihlbl")
        self.tarihedit = QtWidgets.QDateEdit(self.widget)
        self.tarihedit.setGeometry(QtCore.QRect(420, 50, 181, 31))
        self.tarihedit.setAutoFillBackground(False)
        self.tarihedit.setInputMethodHints(QtCore.Qt.ImhDate)
        self.tarihedit.setWrapping(False)
        self.tarihedit.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.tarihedit.setCalendarPopup(True)
        self.tarihedit.setTimeSpec(QtCore.Qt.LocalTime)
        self.tarihedit.setDate(QtCore.QDate.currentDate())
        self.tarihedit.setObjectName("tarihedit")
        self.miktartxt = QtWidgets.QLineEdit(self.widget)
        self.miktartxt.setGeometry(QtCore.QRect(420, 200, 81, 31))
        self.miktartxt.setObjectName("miktartxt")
        self.miktarcombobx = QtWidgets.QComboBox(self.widget)
        self.miktarcombobx.setGeometry(QtCore.QRect(500, 200, 81, 31))
        self.miktarcombobx.setObjectName("miktarcombobx")
        self.miktarcombobx.addItem("")
        self.miktarcombobx.addItem("")
        self.miktarcombobx.addItem("")
        self.miktarlbl = QtWidgets.QLabel(self.widget)
        self.miktarlbl.setGeometry(QtCore.QRect(420, 170, 71, 31))
        self.miktarlbl.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.miktarlbl.setObjectName("miktarlbl")
        self.fiyattxt = QtWidgets.QLineEdit(self.widget)
        self.fiyattxt.setGeometry(QtCore.QRect(420, 260, 81, 31))
        self.fiyattxt.setPlaceholderText("")
        self.fiyattxt.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.fiyattxt.setClearButtonEnabled(False)
        self.fiyattxt.setObjectName("fiyattxt")
        self.fiyatlarcombobx = QtWidgets.QComboBox(self.widget)
        self.fiyatlarcombobx.setGeometry(QtCore.QRect(500, 260, 81, 31))
        self.fiyatlarcombobx.setObjectName("fiyatlarcombobx")
        self.fiyatlarcombobx.addItem("")
        self.fiyatlarcombobx.addItem("")
        self.fiyatlarcombobx.addItem("")
        self.fiyatlbl = QtWidgets.QLabel(self.widget)
        self.fiyatlbl.setGeometry(QtCore.QRect(420, 230, 101, 31))
        self.fiyatlbl.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.fiyatlbl.setObjectName("fiyatlbl")
        self.temizlebtn = QtWidgets.QPushButton(self.widget)
        self.temizlebtn.setGeometry(QtCore.QRect(220, 350, 91, 31))
        self.temizlebtn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 85, 255);")
        self.temizlebtn.setObjectName("temizlebtn")
        self.temizlebtn.clicked.connect(self.temizlecliked)
        self.kydetbtn = QtWidgets.QPushButton(self.widget)
        self.kydetbtn.setGeometry(QtCore.QRect(330, 350, 91, 31))
        self.kydetbtn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 85, 255);")
        self.kydetbtn.setObjectName("kydetbtn")
        self.kydetbtn.clicked.connect(self.tgirdikyt)
        self.tedarikcieklebtn = QtWidgets.QPushButton(self.widget)
        self.tedarikcieklebtn.setGeometry(QtCore.QRect(290, 50, 91, 31))
        self.tedarikcieklebtn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 85, 255);")
        self.tedarikcieklebtn.setObjectName("tedarikcieklebtn")
        self.tedarikcieklebtn.clicked.connect(self.udtkcliked)
        self.giderlbl = QtWidgets.QLabel(Dialog)
        self.giderlbl.setGeometry(QtCore.QRect(270, 10, 111, 31))
        self.tdrkbilgibtn = QtWidgets.QPushButton(self.widget)
        self.tdrkbilgibtn.setGeometry(QtCore.QRect(240, 50, 41, 31))
        self.tdrkbilgibtn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "alternate-background-color: rgb(0, 85, 255);")
        self.tdrkbilgibtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tdrkbilgibtn.setIcon(icon1)
        self.tdrkbilgibtn.setIconSize(QtCore.QSize(20, 20))
        self.tdrkbilgibtn.setObjectName("tdrkbilgibtn")
        self.tdrkbilgibtn.pressed.connect(self.infocliled)
        self.tdrkbilgibtn.released.connect(self.notinfocliked)
        self.tedarikinfolbl = QtWidgets.QLabel(self.widget)
        self.tedarikinfolbl.setGeometry(QtCore.QRect(220, 310, 201, 30))
        self.tedarikinfolbl.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                                          "color: rgb(0, 170, 0);")
        self.tedarikinfolbl.setObjectName("tedarikinfolbl")


        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 45, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 22, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 0, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 0, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 127, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 45, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 22, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 0, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 0, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 127, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 45, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 22, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 0, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 0, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.giderlbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(24)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.giderlbl.setFont(font)
        self.giderlbl.setStyleSheet("color: rgb(170, 0, 0);")
        self.giderlbl.setObjectName("giderlbl")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        ##completer
        db = pymysql.connect(host='127.0.0.1',
                             user='root',
                             password='',
                             db='test',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor
                             )
        baglanti = db.cursor()

        baglanti.execute(f'SELECT TSA FROM tedarikci')
        scomp = baglanti.fetchall()

        names = []
        x = 0

        for i in scomp:
                names.append(scomp[x]['TSA'])
                x += 1

        completer = QtWidgets.QCompleter(names)
        self.tedarikcitxt.setCompleter(completer)



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TEDARİK"))
        self.tedarikcilbl.setText(_translate("Dialog", "TEDARİKÇİ"))
        self.acklamalbl.setText(_translate("Dialog", "AÇIKLAMA"))
        self.urunlercombobx.setItemText(0, _translate("Dialog", "ODUN"))
        self.urunlercombobx.setItemText(1, _translate("Dialog", "FINDIK"))
        self.urunlercombobx.setItemText(2, _translate("Dialog", "UN"))
        self.urunlercombobx.setItemText(3, _translate("Dialog", "BUGDAY"))
        self.urunlercombobx.setItemText(4, _translate("Dialog", "ARPA"))
        self.urunlerlbl.setText(_translate("Dialog", "ÜRÜNLER"))
        self.tarihlbl.setText(_translate("Dialog", "TARİH"))
        self.miktarcombobx.setItemText(0, _translate("Dialog", "Kilogram"))
        self.miktarcombobx.setItemText(1, _translate("Dialog", "Gram"))
        self.miktarcombobx.setItemText(2, _translate("Dialog", "Litre"))
        self.miktarlbl.setText(_translate("Dialog", " MİKTAR"))
        self.fiyatlarcombobx.setItemText(0, _translate("Dialog", "Türk Lirası ₺"))
        self.fiyatlarcombobx.setItemText(1, _translate("Dialog", "Dolar $"))
        self.fiyatlarcombobx.setItemText(2, _translate("Dialog", "Euro €"))
        self.fiyatlbl.setText(_translate("Dialog", "BİRİM FİYATI"))
        self.temizlebtn.setText(_translate("Dialog", "Temizle"))
        self.kydetbtn.setText(_translate("Dialog", "Kaydet"))
        self.tedarikcieklebtn.setText(_translate("Dialog", "TEDARİKÇİ EKLE"))
        self.giderlbl.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" color:#aa0000;\">GİDER</span></p></body></html>"))
        self.giderlbl.setWhatsThis(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-style:italic; text-decoration: underline; color:#ff0000;\">GELİR</span></p></body></html>"))
        self.giderlbl.setText(_translate("Dialog", "TEDARİK"))


    def udtkcliked(self):

        self.tkDialog = QtWidgets.QDialog()
        self.ui = UDTK.Ui_Dialog()
        self.ui.setupUi(self.tkDialog)
        self.tkDialog.show()



    def tgirdikyt(self):
       try:
        _translate = QtCore.QCoreApplication.translate
        self.tedarikinfolbl.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                                          "color: rgb(0, 170, 0);")
        self.tedarikinfolbl.setText(_translate("Dialog", "Tedarik başarıyla kaydedildi."))
        db = pymysql.connect(host='127.0.0.1',
                             user='root',
                             password='',
                             db='test',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor
                             )
        baglanti = db.cursor()
        tidtxt = self.tedarikcitxt.text()
        baglanti.execute(f'SELECT TID FROM tedarikci WHERE TSA="{tidtxt}" ')
        index = baglanti.fetchall()
        tid = int(index[0]['TID'])
        uidtxt = str(self.urunlercombobx.currentText())
        baglanti.execute(f'SELECT UID FROM urunler WHERE  UrunAd="{uidtxt}" ')
        uindex = baglanti.fetchall()
        uid = int(uindex[0]['UID'])
        umiktar = int(self.miktartxt.text())
        umiktarbirim = str(self.miktarcombobx.currentText())
        ubirimfiyat = int(self.fiyattxt.text())
        ufiyatbirim = str(self.fiyatlarcombobx.currentText())
        gtarih = self.tarihedit.date().toPyDate()
        gaciklama = self.acklamatxt.toPlainText()
        tutar=umiktar*ubirimfiyat
        baglanti.execute(
            f"INSERT INTO tedarikgirdi (TID,UID,UMiktar,UBirimtur,Ubirimfiyati,Ufiyattur,GTTarih,TAcıklama,TTutar) VALUES ('{tid}','{uid}','{umiktar}','{umiktarbirim}','{ubirimfiyat}','{ufiyatbirim}','{gtarih}','{gaciklama}','{tutar}')")

        db.commit()
        if str(self.urunlercombobx.currentText())=='FINDIK':
            baglanti.execute('SELECT SUM(UMiktar) FROM tedarikgirdi WHERE UID="1"')
            updtadepo1 = baglanti.fetchall()
            ss1 = int(updtadepo1[0]['SUM(UMiktar)'])
            ##
            baglanti.execute('SELECT SUM(UMiktar) FROM musterigirdi WHERE UID="1"')
            mupdtadepo1 = baglanti.fetchall()
            mss = int(mupdtadepo1[0]['SUM(UMiktar)'])
            mtss = ss1 - mss
            baglanti.execute(f"UPDATE depo SET UStok='{mtss}' WHERE UID='1'")
            db.commit()

        elif str(self.urunlercombobx.currentText())=='ODUN':
            baglanti.execute('SELECT SUM(UMiktar) FROM tedarikgirdi WHERE UID="2"')
            updtadepo2 = baglanti.fetchall()
            ss2 = int(updtadepo2[0]['SUM(UMiktar)'])
            baglanti.execute('SELECT SUM(UMiktar) FROM musterigirdi WHERE UID="2"')
            mupdtadepo2 = baglanti.fetchall()
            mss1 = int(mupdtadepo2[0]['SUM(UMiktar)'])
            mtss1 = ss2 - mss1
            baglanti.execute(f"UPDATE depo SET UStok='{mtss1}' WHERE UID='2'")
            db.commit()
        elif str(self.urunlercombobx.currentText())=='BUGDAY':
            baglanti.execute('SELECT SUM(UMiktar) FROM tedarikgirdi WHERE UID="3"')
            updtadepo3 = baglanti.fetchall()
            ss3 = int(updtadepo3[0]['SUM(UMiktar)'])
            baglanti.execute('SELECT SUM(UMiktar) FROM musterigirdi WHERE UID="3"')
            mupdtadepo3 = baglanti.fetchall()
            mss2 = int(mupdtadepo3[0]['SUM(UMiktar)'])
            mtss2 = ss3 - mss2
            baglanti.execute(f"UPDATE depo SET UStok='{mtss2}' WHERE UID='3'")
            db.commit()

        elif str(self.urunlercombobx.currentText())=='ARPA':
            baglanti.execute('SELECT SUM(UMiktar) FROM tedarikgirdi WHERE UID="4"')
            updtadepo4 = baglanti.fetchall()
            ss4 = int(updtadepo4[0]['SUM(UMiktar)'])
            baglanti.execute('SELECT SUM(UMiktar) FROM musterigirdi WHERE UID="4"')
            mupdtadepo4 = baglanti.fetchall()
            mss3 = int(mupdtadepo4[0]['SUM(UMiktar)'])
            mtss3 = ss4 - mss3
            baglanti.execute(f"UPDATE depo SET UStok='{mtss3}' WHERE UID='4'")
            db.commit()
        elif str(self.urunlercombobx.currentText())=='UN':
            baglanti.execute('SELECT SUM(UMiktar) FROM tedarikgirdi WHERE UID="5"')
            updtadepo5 = baglanti.fetchall()
            ss5 = int(updtadepo5[0]['SUM(UMiktar)'])
            baglanti.execute('SELECT SUM(UMiktar) FROM musterigirdi WHERE UID="5"')
            mupdtadepo5 = baglanti.fetchall()
            mss4 = int(mupdtadepo5[0]['SUM(UMiktar)'])
            mtss4 = ss5 - mss4
            baglanti.execute(f"UPDATE depo SET UStok='{mtss4}' WHERE UID='5'")
            db.commit()








       except ValueError as e:
           self.tedarikinfolbl.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
                                             "color: rgb(255, 0, 0);")
           self.tedarikinfolbl.setText(_translate("Dialog", f"Başında yıldız olan alanlar boş bırakılamaz!"))
       except IndexError as f:
           self.tedarikinfolbl.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
                                             "color: rgb(255, 0, 0);")
           self.tedarikinfolbl.setText(_translate("Dialog", f"Böyle bir tedarikçi kayıt edilmemiş\nÖnce kayıt ediniz"))



    def temizlecliked(self):
        _translate = QtCore.QCoreApplication.translate
        self.tedarikinfolbl.setText(_translate("Dialog", ""))
        self.tedarikcitxt.setText("")
        self.acklamatxt.setText("")
        self.miktartxt.setText("")
        self.fiyattxt.setText("")
        self.tarihedit.setDate(QtCore.QDate.currentDate())
        self.miktarcombobx.setCurrentIndex(0)
        self.fiyatlarcombobx.setCurrentIndex(0)
        self.urunlercombobx.setCurrentIndex(0)

    def infocliled(self):
        ##database insert
        db = pymysql.connect(host='127.0.0.1',
                             user='root',
                             password='',
                             db='test',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor
                             )
        baglanti = db.cursor()


        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(30, 81, 251, 151))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "background-color: rgb(188, 189, 198);\n"
                                 "")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
                                 "font: 75 8pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 25, 161, 21))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 50, 171, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(0, 110, 181, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(0, 75, 171, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(70, 0, 111, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(70, 25, 181, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(70, 50, 191, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(70, 75, 171, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(70, 100, 171, 51))
        self.label_10.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_10.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")


        self.label.setText(( "Şirket Adı :"))
        self.label_2.setText( "Şirket Tel :")
        self.label_3.setText( "Şirket Email :")
        self.label_4.setText( "Şirket Adres :")
        self.label_5.setText( "Şirket İl/İlçe:")

        tidtxt = self.tedarikcitxt.text()
        baglanti.execute(f'SELECT TSA,TTel,TEmail,Til,Tilce,TAdres FROM tedarikci WHERE TSA="{tidtxt}" ')
        isim =baglanti.fetchall()
        if self.tedarikcitxt.text()=='':
            self.label_6.setText("")
            self.label_7.setText("")
            self.label_8.setText("")
            self.label_9.setText("")
            self.label_10.setText("")
        else:
            self.label_6.setText( f"{isim[0]['TSA']}")
            self.label_7.setText( f"{isim[0]['TTel']}")
            self.label_8.setText( f"{isim[0]['TEmail']}")
            self.label_9.setText( f"{isim[0]['Til']}/{isim[0]['Tilce']}")
            self.label_10.setText( f"{isim[0]['TAdres']}")

        self.frame.show()

    def notinfocliked(self):
        self.frame.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tDialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(tDialog)
    tDialog.show()
    sys.exit(app.exec_())
