# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'girisdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
import UM
import UCP

db= pymysql.connect(host='127.0.0.1',
                    user='root',
                    password='',
                    db='test',
                    charset='utf8mb4',
                    cursorclass=pymysql.cursors.DictCursor
                    )
baglanti=db.cursor()

class Ui_GirisEkran(object):
    def setupUi(self, GirisEkran):
        GirisEkran.setObjectName("GirisEkran")
        GirisEkran.resize(305, 320)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        GirisEkran.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/wheat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GirisEkran.setWindowIcon(icon)
        GirisEkran.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(85, 170, 255);")
        self.falsesfrealert = QtWidgets.QLabel(GirisEkran)
        self.falsesfrealert.setGeometry(QtCore.QRect(90, 155, 141, 20))
        self.falsesfrealert.setStyleSheet("color: rgb(255, 0, 0);\n""font: 8pt \"MS Shell Dlg 2\";\n"
                                    "")
        self.falsesfrealert.setText("")
        self.falsesfrealert.setObjectName("falsesfrealert")
        self.passwordtxt = QtWidgets.QLineEdit(GirisEkran)
        self.passwordtxt.setGeometry(QtCore.QRect(90, 180, 131, 20))
        self.passwordtxt.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.passwordtxt.setObjectName("passwordtxt")
        self.passwordtxt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pushButton = QtWidgets.QPushButton(GirisEkran)
        self.pushButton.setGeometry(QtCore.QRect(120, 220, 75, 31))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 85, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.clicked)
        self.bglbl = QtWidgets.QLabel(GirisEkran)
        self.bglbl.setGeometry(QtCore.QRect(80, 20, 141, 131))
        self.bglbl.setText("")
        self.bglbl.setPixmap(QtGui.QPixmap("icons/Başlıksız-12222btk.png"))
        self.bglbl.setScaledContents(True)
        self.bglbl.setObjectName("bglbl")
        self.bglbl.raise_()
        self.passwordtxt.raise_()
        self.pushButton.raise_()

        self.retranslateUi(GirisEkran)
        QtCore.QMetaObject.connectSlotsByName(GirisEkran)

    def retranslateUi(self, GirisEkran):
        _translate = QtCore.QCoreApplication.translate
        GirisEkran.setWindowTitle(_translate("GirisEkran", "Dialog"))
        self.passwordtxt.setPlaceholderText(_translate("GirisEkran", "Şifrenizi Giriniz"))
        self.pushButton.setText(_translate("GirisEkran", "Giriş"))

    def clicked (self):
        baglanti.execute(f'SELECT Id FROM password WHERE Id="1" ')
        index = baglanti.fetchall()
        if len(index) == 1:
          baglanti.execute("SELECT * FROM password WHERE Id='1'")
          ss = baglanti.fetchall()
        if self.passwordtxt.text()==str(ss[0]['psword']):

            self.MainWindow = QtWidgets.QMainWindow()
            self.ui = UM.Ui_MainWindow()
            self.ui.setupUi(self.MainWindow)

            self.MainWindow.show()
            GirisEkran.hide()






        else:
             self.falsesfrealert.setText('!Yanlış şifre tekrar deneyiniz.')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GirisEkran = QtWidgets.QDialog()
    ui = Ui_GirisEkran()
    ui.setupUi(GirisEkran)
    GirisEkran.show()
    sys.exit(app.exec_())
